name: Frontend Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  run-jest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install npm dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run Jest Tests
      working-directory: ./frontend
      run: npm test